import 'package:flutter/material.dart';

import '../../core/constants/app_constants.dart';
import '../../core/utils/responsive.dart';

/// §53. What this app is and how the numbers in it are worked out.
class AboutScreen extends StatelessWidget {
  const AboutScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('About')),
      body: ListView(
        padding: Responsive.pagePadding(context),
        children: <Widget>[
          Center(
            child: Column(
              children: <Widget>[
                Container(
                  height: 72,
                  width: 72,
                  decoration: BoxDecoration(
                    color: theme.colorScheme.primary,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Icon(
                    Icons.confirmation_number_rounded,
                    size: 36,
                    color: theme.colorScheme.onPrimary,
                  ),
                ),
                const SizedBox(height: 14),
                Text(AppConstants.appName, style: theme.textTheme.titleLarge),
                Text(
                  'Version 1.0.0',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 28),
          _Block(
            title: 'What it does',
            body: 'SmartQueue replaces physical queueing at service desks. You take a '
                'numbered ticket from your phone, watch your position update while you '
                'wait somewhere comfortable, and come back when you are called.',
          ),
          _Block(
            title: 'How the wait time is estimated',
            body: 'people ahead of you × the average time one person takes ÷ the number '
                'of counters currently open. The average starts from the service\'s '
                'configured figure and shifts towards what has actually been measured '
                'today once there are enough completed visits to trust it.',
          ),
          _Block(
            title: 'One ticket at a time',
            body: 'You can hold one active ticket per service. That rule is enforced by a '
                'unique index in the database, not just by this app, so it holds even if '
                'two taps arrive at the same instant.',
          ),
          _Block(
            title: 'Where the numbers come from',
            body: 'Every figure on every screen is read from the server. Ticket numbers '
                'are generated by the database inside a transaction — the app never '
                'invents one.',
          ),
          const SizedBox(height: 20),
          Text(
            'Built as a university project: Flutter · Node.js · Express · MySQL.',
            textAlign: TextAlign.center,
            style: theme.textTheme.labelSmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }
}

class _Block extends StatelessWidget {
  const _Block({required this.title, required this.body});

  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(title, style: theme.textTheme.titleSmall),
          const SizedBox(height: 6),
          Text(body, style: theme.textTheme.bodyMedium),
        ],
      ),
    );
  }
}
